import {
	brainstormQuestion,
	showerQuestion,
	coffeeQuestion,
	snackQuestion,
	dayOffQuestion,
	badDayQuestion,
	doorOpenQuestion,
	mitesQuestion,
	eatQuestion,
	pestQuestion,
	doorQuestion,
	messQuestion,
	closetQuestion,
	flyingQuestion,
	talkQuestion,
	nightQuestion,
	catepillarQuestion,
	runningQuestion,
	collarQuestion,
	pocketQuestion,
	stomachQuestion,
	walkQuestion,
	drivewayQuestion,
	sleepQuestion,
	morningQuestion,
	picnicQuestion,
	pileaQuestion,
	dinnerQuestion,
	decompressQuestion,
	rechargeQuestion,
} from '@/data/questions';

const allQuestions = [
	brainstormQuestion,
	showerQuestion,
	coffeeQuestion,
	snackQuestion,
	dayOffQuestion,
	badDayQuestion,
	doorOpenQuestion,
	mitesQuestion,
	eatQuestion,
	pestQuestion,
	doorQuestion,
	messQuestion,
	closetQuestion,
	flyingQuestion,
	talkQuestion,
	nightQuestion,
	catepillarQuestion,
	runningQuestion,
	collarQuestion,
	pocketQuestion,
	stomachQuestion,
	walkQuestion,
	drivewayQuestion,
	sleepQuestion,
	morningQuestion,
	picnicQuestion,
	pileaQuestion,
	dinnerQuestion,
	decompressQuestion,
	rechargeQuestion,
].sort((a, b) => a.position - b.position);

export const firstQuestion = brainstormQuestion;

export function getNextQuestion(currentQuestion) {
	const nextPosition = currentQuestion.position + 1;
	return allQuestions.find((q) => q.position === nextPosition);
}
